#!/bin/sh
lock() {
#    xwobf -s 10 /dev/shm/.i3lock.png
#    ~/scripts/i3lock-color.sh -i /dev/shm/.i3lock.png
     #~/bin/rand
     ~/scripts/i3lock-color.sh -i ~/.config/i3/lockscreen.png
}


case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
